# feature_selection/02_extract_candidate_matrix.py
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import warnings

warnings.filterwarnings('ignore')

# ==============================================================================
# GT-Mamba Feature Selection - Stage 2: Candidate Matrix Extraction
# Purpose: Extract the top 5000 candidate CpG features across all 10 cohorts
#          and merge them into a single standardized matrix for training.
# ==============================================================================

# 1. Automatically locate the project root directory
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(CURRENT_DIR)

# Configure adaptive paths
DATA_DIR = os.path.join(BASE_DIR, "data", "processed_data")
FEAT_LIST_PATH = os.path.join(BASE_DIR, "results", "feature_selection", "top_5000_partial_corr_cpgs.csv")
REF_SPLIT_FILE = os.path.join(BASE_DIR, "data", "final_merged_cpg140_matrix.csv")
OUTPUT_PATH = os.path.join(BASE_DIR, "results", "feature_selection", "top5000_merged_matrix.csv")

# 10 Discovery Cohorts
GEO_LIST = [
    'GSE40279', 'GSE53128', 'GSE55763', 'GSE60132', 'GSE64495',
    'GSE65638', 'GSE72773', 'GSE72775', 'GSE73103', 'GSE87571'
]


def main():
    # --- Step 1: Load Split Reference Information ---
    print(f"📥 Loading split reference: {os.path.basename(REF_SPLIT_FILE)}")
    ref_df = pd.read_csv(REF_SPLIT_FILE)

    # Intelligently identify ID and Split columns
    id_col = next((c for c in ref_df.columns if c.lower() in ['id', 'sampleid']), ref_df.columns[0])
    split_col = next((c for c in ref_df.columns if c.lower() in ['split', 'group']), None)

    ref_df[id_col] = ref_df[id_col].astype(str).str.lower().str.strip()
    id_split_map = dict(zip(ref_df[id_col], ref_df[split_col]))

    # --- Step 2: Load Top 5000 Feature List ---
    print(f"📥 Loading target features: {os.path.basename(FEAT_LIST_PATH)}")

    # Compatibility processing: Use 'cpg' column if generated by Stage 1, otherwise use the first column
    feat_df = pd.read_csv(FEAT_LIST_PATH)
    selected_features = feat_df['cpg'].tolist() if 'cpg' in feat_df.columns else feat_df.iloc[:, 0].tolist()
    print(f"✅ Target features to extract: {len(selected_features)}")

    # --- Step 3: Multi-cohort Parallel Merging ---
    all_dfs = []

    for gse in tqdm(GEO_LIST, desc="Merging Cohorts"):
        beta_file = os.path.join(DATA_DIR, f"{gse}_beta.csv")
        pheno_file = os.path.join(DATA_DIR, f"{gse}_pheno.csv")

        if not os.path.exists(beta_file) or not os.path.exists(pheno_file):
            continue

        # Read and standardize indices
        beta_df = pd.read_csv(beta_file, index_col=0).T
        pheno_df = pd.read_csv(pheno_file, index_col=0)

        beta_df.index = beta_df.index.str.lower().str.strip()
        pheno_df.index = pheno_df.index.str.lower().str.strip()
        beta_df.index.name = 'ID'

        # Three-way alignment (Beta ∩ Pheno ∩ SplitMap)
        valid_samples = [s for s in beta_df.index.intersection(pheno_df.index) if s in id_split_map]
        if not valid_samples: continue

        # Extract subset
        beta_sub = beta_df.loc[valid_samples].copy()

        # Inject metadata
        beta_sub['Split'] = [id_split_map[s] for s in valid_samples]
        beta_sub['Dataset'] = gse

        # Standardize Age unit to Years
        if "Age_unit" in pheno_df.columns:
            unit = str(pheno_df.loc[valid_samples, "Age_unit"].iloc[0]).lower()
            age = pheno_df.loc[valid_samples, "Age"].astype(float)
            if "month" in unit:
                age /= 12
            elif "week" in unit:
                age /= 52
            elif "day" in unit:
                age /= 365
            beta_sub['Age'] = age
        else:
            beta_sub['Age'] = pheno_df.loc[valid_samples, 'Age'].values

        # Retain only features that exist in both the Top 5000 list and the current dataset
        features_in_data = [c for c in selected_features if c in beta_sub.columns]
        meta_cols = ['Age', 'Dataset', 'Split']
        beta_sub = beta_sub[meta_cols + features_in_data].dropna()

        all_dfs.append(beta_sub)

    # --- Step 4: Save Final Matrix ---
    if all_dfs:
        print("🔄 Concatenating all fragments...")
        final_matrix = pd.concat(all_dfs, axis=0).reset_index()

        # Standardize column names
        if 'ID' not in final_matrix.columns:
            final_matrix.rename(columns={'index': 'ID'}, inplace=True)

        # Reorder columns: ID, Age, Dataset, Split, [CpGs...]
        ordered_meta = ['ID', 'Age', 'Dataset', 'Split']
        cpg_cols = [c for c in final_matrix.columns if c not in ordered_meta]
        final_matrix = final_matrix[ordered_meta + cpg_cols]

        os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
        final_matrix.to_csv(OUTPUT_PATH, index=False)
        print(f"🎉 Success! Candidate matrix saved: {OUTPUT_PATH}")
        print(f"📊 Final Shape: {final_matrix.shape}")
    else:
        print("❌ Error: No data merged. Check input files and sample IDs.")


if __name__ == "__main__":
    main()